### ISSUE TITLE
Get-CoinbaseProducts could use a -Filter

### ISSUE THREAD

**Issue by jasonpearce** [Invertee/GDAX-Powershell#2]
Get-CoinbaseProdcuts returns all products. To filter, I have to pipe to a Where-Object. I'd like to do more just within the commadlet.

# This Works: Get a list of USD trading pairs (but exclude USDC trading pairs)
Get-CoinbaseProducts | Where {$_.ID -like "*-USD" -and $_.ID -notlike "*-USDC"} | Sort ID | FT -AutoSize

# Wish list: But these options would be nice to have
Get-CoinbaseProducts -Filter {ID -like "*-USD" -and ID -notlike "*-USDC"}
Get-CoinbaseProdcuts -ID BTC-USD,ETH-USD,LTC-USD

**Comment by Invertee** [comment]
I added that in after all, just a simple filter param that accepts a script block like so:
`Get-CoinbaseProProducts -Filter {$_.id -like "*LTC"}`
