### ISSUE TITLE
Get-CoinbaseProductTicker fails to return the price of many trading pairs

### ISSUE THREAD

**Issue by jasonpearce** [Invertee/GDAX-Powershell#3]
For starters, it appears the only valid ProdcutID values this commandlet will accept are:

BTC-GBP,BTC-EUR,ETH-BTC,ETH-EUR,LTC-BTC,LTC-EUR,LTC-USD,ETH-USD,BTC-USD,BCH-USD

But Coinbase has more products.  Get-CoinbaseProducts | Select ID | Sort ID provides these prodcut IDs:

id
--
BAT-USDC
BCH-BTC
BCH-EUR
BCH-GBP
BCH-USD
BTC-EUR
BTC-GBP
BTC-USD
BTC-USDC
CVC-USDC
DAI-USDC
DNT-USDC
ETC-BTC
ETC-EUR
ETC-GBP
ETC-USD
ETH-BTC
ETH-EUR
ETH-GBP
ETH-USD
ETH-USDC
GNT-USDC
LOOM-USDC
LTC-BTC
LTC-EUR
LTC-GBP
LTC-USD
MANA-USDC
MKR-USDC
ZEC-USDC
ZIL-USDC
ZRX-BTC
ZRX-EUR
ZRX-USD

If I run each one of these, most will fail: 

Get-CoinbaseProductTicker -ProductID BAT-USDC
Get-CoinbaseProductTicker -ProductID BCH-BTC
Get-CoinbaseProductTicker -ProductID BCH-EUR
Get-CoinbaseProductTicker -ProductID BCH-GBP
Get-CoinbaseProductTicker -ProductID BCH-USD
Get-CoinbaseProductTicker -ProductID BTC-EUR
Get-CoinbaseProductTicker -ProductID BTC-GBP
Get-CoinbaseProductTicker -ProductID BTC-USD
Get-CoinbaseProductTicker -ProductID BTC-USDC
Get-CoinbaseProductTicker -ProductID CVC-USDC
Get-CoinbaseProductTicker -ProductID DAI-USDC
Get-CoinbaseProductTicker -ProductID DNT-USDC
Get-CoinbaseProductTicker -ProductID ETC-BTC
Get-CoinbaseProductTicker -ProductID ETC-EUR
Get-CoinbaseProductTicker -ProductID ETC-GBP
Get-CoinbaseProductTicker -ProductID ETC-USD
Get-CoinbaseProductTicker -ProductID ETH-BTC
Get-CoinbaseProductTicker -ProductID ETH-EUR
Get-CoinbaseProductTicker -ProductID ETH-GBP
Get-CoinbaseProductTicker -ProductID ETH-USD
Get-CoinbaseProductTicker -ProductID ETH-USDC
Get-CoinbaseProductTicker -ProductID GNT-USDC
Get-CoinbaseProductTicker -ProductID LOOM-USDC
Get-CoinbaseProductTicker -ProductID LTC-BTC
Get-CoinbaseProductTicker -ProductID LTC-EUR
Get-CoinbaseProductTicker -ProductID LTC-GBP
Get-CoinbaseProductTicker -ProductID LTC-USD
Get-CoinbaseProductTicker -ProductID MANA-USDC
Get-CoinbaseProductTicker -ProductID MKR-USDC
Get-CoinbaseProductTicker -ProductID ZEC-USDC
Get-CoinbaseProductTicker -ProductID ZIL-USDC
Get-CoinbaseProductTicker -ProductID ZRX-BTC
Get-CoinbaseProductTicker -ProductID ZRX-EUR
Get-CoinbaseProductTicker -ProductID ZRX-USD

How do I get pricing information for the trading pairs that fail?

**Comment by Invertee** [comment]
Module now retrieves product pairs on import.
