### ISSUE TITLE
Get-CoinbaseProAccount (plural or not plural?)

### ISSUE THREAD

**Issue by jasonpearce** [Invertee/GDAX-Powershell#6]
On this page, https://github.com/Invertee/CoinbasePro-Powershell, the cmdlet is singular: Get-CoinbaseProAccount. But in the module, it's plural: Get-CoinbaseProAccounts. To be consistent, however, perhaps Get-CoinbaseAccount and Get-CoinbaseProAccounts should both be singular (or both plural). I'm still learning what they do. At least the documentation on GitHub and the cmdlet are not consistent and I thought you'd like to know. Thank you.

# Valid CmdLets
Get-Help Get-Coinbase* | Sort Name | Select Name

Name
----
**Get-CoinbaseAccount**
Get-CoinbaseAccountHistory
Get-CoinbaseAccountHolds
Get-CoinbaseAccounts
Get-CoinbaseCurrencies
Get-CoinbaseFills
Get-CoinbaseOrder
Get-CoinbaseOrders
Get-CoinbaseProAccountHistory
**Get-CoinbaseProAccounts**
Get-CoinbaseProCurrencies
Get-CoinbaseProductOrderBook
Get-CoinbaseProducts
Get-CoinbaseProductStats
Get-CoinbaseProductTicker
Get-CoinbaseProductTrades
Get-CoinbaseProFees
Get-CoinbaseProFills
Get-CoinbaseProOrder
Get-CoinbaseProOrders
Get-CoinbaseProPaymentMethods
Get-CoinbaseProProductOrderBook
Get-CoinbaseProProducts
Get-CoinbaseProProductStats
Get-CoinbaseProProductTicker
Get-CoinbaseProProductTrades
Get-CoinbaseProTime
Get-CoinbaseTime

**Comment by Invertee** [comment]
It looks like you've got an outdated version of the module installed at the same time, `Get-Help *Coinbase* | Sort Name | Select Name` should return this list of functions:
* Get-CoinbaseAccounts
* Get-CoinbaseProAccountHistory
* Get-CoinbaseProAccounts
* Get-CoinbaseProCurrencies
* Get-CoinbaseProFees
* Get-CoinbaseProFills
* Get-CoinbaseProOrder
* Get-CoinbaseProOrders
* Get-CoinbaseProPaymentMethods
* Get-CoinbaseProProductOrderBook
* Get-CoinbaseProProducts
* Get-CoinbaseProProductStats
* Get-CoinbaseProProductTicker
* Get-CoinbaseProProductTrades
* Get-CoinbaseProTime
* Invoke-CoinbaseProDeposit
* Invoke-CoinbaseProWithdrawal
* New-CoinbaseProLimitOrder
* New-CoinbaseProMarketOrder
* New-CoinbaseProStopOrder
* Remove-CoinbaseProOrder

Both `Get-CoinbaseAccounts` and `Get-CoinbaseProAccounts` both all available accounts but `Get-CoinbaseProAccounts` has an additional parameter so you can specify the account id and only return that one. I've fixed the readme to clarify.

I need to do a readme in each function so it's available in get-help, but there is already an issue for that!
